/* eslint-disable */
require('./android')
require('./apple-logo')
require('./appstore')
require('./arrow_scroll')
require('./arrow')
require('./btn-arrow')
require('./checkmark')
require('./close')
require('./googleplay')
require('./instruments')
require('./logo')
require('./menu_icon')
require('./settings')
require('./share')
